import type { NextPage } from 'next';
import Head from 'next/head';
import ContactForm from '../components/ContactForm';

const Contact: NextPage = () => {
  return (
    <>
      <Head>
        <title>CIEL Stake Pool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-gradient-to-br from-green-300 via-blue-500 to-purple-600">
        <ContactForm />
      </div>
    </>
  );
};

export default Contact;
